### PR TITLE
Fixed Rendering issue that caused the images to be only partially rendered

### LINKED ISSUE #378: Diva only renders the first row of tiles to a page
Only part of the image is rendered when zoom > 2

### PR DESCRIPTION
**Pull request by zeyadhazem**
The problem was in the definition of the _map property in the
TileCoverageMap class (Syntax) that caused problems while accessing the
multidimensional array. Fixes #378

### CODE REVIEW

File: source/js/tile-coverage-map.js [hunk 1]
```diff
@@ -4,9 +4,7 @@ export default class TileCoverageMap
     {
         this._rows = rows;
         this._cols = cols;
-        // this._map = rows.fill(cols);
-        // this._map = fill(rows).map(() => fill(cols, false));
-        this._map = new Array(rows).fill(new Array(cols).fill(false));
+        this._map = new Array(rows).fill().map(() => new Array(cols).fill(false));
```
Comment (ahankinson) [inline source/js/tile-coverage-map.js]: IntelliJ is giving me a warning about not enough arguments to `fill()`. Is it giving that for you too?

Comment (zeyadhazem) [inline source/js/tile-coverage-map.js]: No only the thick arrow and the warning is that it's only available for ES6, no other warnings. (From JSHint)

**Comment by ahankinson** [comment]
Looks good. Thanks!
